import 'package:flutter/material.dart';


// 1. ADD THIS CLASS DEFINITION (This fixes all 127 errors)
class Video {
  String title;
  String url;
  bool done;

  Video(this.title, this.url, {this.done = false});
}

List<Video> videos = [
  Video("Free CCNA | Network Devices | Day 1 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=1"),
  Video("Free CCNA | Anki Flashcards | Day 1 Extra | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=2"),
  Video("Free CCNA | Packet Tracer Introduction | Day 1 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=3"),
  Video("Free CCNA | Interfaces and Cables | Day 2 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=4"),
  Video("Free CCNA | Connecting Devices | Day 2 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=5"),
  Video("How the TCP/IP Model Actually Works | CCNA Day 3", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=6"),
  Video("Free CCNA | OSI Model | Day 3 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=7"),
  Video("Free CCNA | Intro to the CLI | Day 4 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=8"),
  Video("Free CCNA | Basic Device Security | Day 4 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=9"),
  Video("Free CCNA | Ethernet LAN Switching (Part 1) | Day 5 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=10"),
  Video("Free CCNA | Ethernet LAN Switching (Part 2) | Day 6 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=11"),
  Video("Free CCNA | Analyzing Ethernet Switching | Day 6 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=12"),
  Video("Free CCNA | IPv4 Addressing (Part 1) | Day 7 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=13"),
  Video("Free CCNA | IPv4 Addressing (Part 2) | Day 8 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=14"),
  Video("Free CCNA | Configuring IP Addresses | Day 8 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=15"),
  Video("Free CCNA | Switch Interfaces | Day 9 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=16"),
  Video("Free CCNA | Configuring Interfaces | Day 9 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=17"),
  Video("Free CCNA | IPv4 Header | Day 10 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=18"),
  Video("Free CCNA | Routing Fundamentals | Day 11 (part 1) | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=19"),
  Video("Free CCNA | Static Routing | Day 11 (part 2) | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=20"),
  Video("Free CCNA | Configuring Static Routes | Day 11 Lab 1 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=21"),
  Video("Free CCNA | Troubleshooting Static Routes | Day 11 Lab 2 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=22"),
  Video("Free CCNA | The Life of a Packet | Day 12 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=23"),
  Video("Free CCNA | Life of a Packet | Day 12 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=24"),
  Video("Free CCNA | Subnetting (Part 1) | Day 13 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=25"),
  Video("Free CCNA | Subnetting (Part 2) | Day 14 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=26"),
  Video("Free CCNA | Subnetting (Part 3 - VLSM) | Day 15 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=27"),
  Video("Free CCNA | Subnetting (VLSM) | Day 15 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=28"),
  Video("Free CCNA | VLANs (Part 1) | Day 16 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=29"),
  Video("Free CCNA | VLANs (Part 1) | Day 16 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=30"),
  Video("Free CCNA | VLANs (Part 2) | Day 17 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=31"),
  Video("Free CCNA | VLANs (Part 2) | Day 17 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=32"),
  Video("Free CCNA | VLANs (Part 3) | Day 18 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=33"),
  Video("Free CCNA | VLANs (Part 3) | Day 18 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=34"),
  Video("Free CCNA | DTP/VTP | Day 19 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=35"),
  Video("Free CCNA | DTP/VTP | Day 19 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=36"),
  Video("Free CCNA | Spanning Tree Protocol (Part 1) | Day 20 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=37"),
  Video("Free CCNA | Analyzing STP | Day 20 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=38"),
  Video("Free CCNA | Spanning Tree Protocol (Part 2) | Day 21 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=39"),
  Video("PortFast (STP Toolkit) | CCNA 200-301 Day 21 (part 1)", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=40"),
  Video("BPDU Guard & BPDU Filter (STP Toolkit) | CCNA 200-301 Day 21 (part 2)", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=41"),
  Video("Root Guard (STP Toolkit) | CCNA 200-301 Day 21 (part 3)", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=42"),
  Video("Loop Guard (STP Toolkit) | CCNA 200-301 Day 21 (part 4)", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=43"),
  Video("Free CCNA | Configuring STP (PVST+) | Day 21 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=44"),
  Video("Free CCNA | Rapid Spanning Tree Protocol | Day 22 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=45"),
  Video("Free CCNA | Rapid STP | Day 22 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=46"),
  Video("Free CCNA | EtherChannel | Day 23 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=47"),
  Video("Free CCNA | Configuring EtherChannel | Day 23 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=48"),
  Video("Free CCNA | Dynamic Routing | Day 24 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=49"),
  Video("Free CCNA | Floating Static Routes | Day 24 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=50"),
  Video("Free CCNA | RIP & EIGRP | Day 25 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=51"),
  Video("Free CCNA | Configuring EIGRP | Day 25 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=52"),
  Video("Free CCNA | OSPF Part 1 | Day 26 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=53"),
  Video("Free CCNA | Configuring OSPF (1) | Day 26 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=54"),
  Video("Free CCNA | OSPF Part 2 | Day 27 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=55"),
  Video("Free CCNA | Configuring OSPF (2) | Day 27 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=56"),
  Video("Free CCNA | OSPF Part 3 | Day 28 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=57"),
  Video("Free CCNA | Configuring OSPF (3) | Day 28 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=58"),
  Video("Free CCNA | First Hop Redundancy Protocols | Day 29 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=59"),
  Video("Free CCNA | Configuring HSRP | Day 29 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=60"),
  Video("Free CCNA | TCP & UDP | Day 30 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=61"),
  Video("Free CCNA | Wireshark Demo (TCP/UDP) | Day 30 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=62"),
  Video("Free CCNA | IPv6 Part 1 | Day 31 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=63"),
  Video("Free CCNA | Configuring IPv6 (Part 1) | Day 31 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=64"),
  Video("Free CCNA | IPv6 Part 2 | Day 32 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=65"),
  Video("Free CCNA | Configuring IPv6 (Part 2) | Day 32 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=66"),
  Video("Free CCNA | IPv6 Part 3 | Day 33 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=67"),
  Video("Free CCNA | Configuring IPv6 (Part 3) | Day 33 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=68"),
  Video("Free CCNA | Standard ACLs | Day 34 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=69"),
  Video("Free CCNA | Standard ACLs | Day 34 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=70"),
  Video("Free CCNA | Extended ACLs | Day 35 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=71"),
  Video("Free CCNA | Extended ACLs | Day 35 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=72"),
  Video("Free CCNA | CDP & LLDP | Day 36 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=73"),
  Video("Free CCNA | CDP & LLDP | Day 36 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=74"),
  Video("Free CCNA | NTP | Day 37 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=75"),
  Video("Free CCNA | NTP | Day 37 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=76"),
  Video("Free CCNA | DNS | Day 38 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=77"),
  Video("Free CCNA | DNS | Day 38 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=78"),
  Video("Free CCNA | DHCP | Day 39 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=79"),
  Video("Free CCNA | DHCP | Day 39 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=80"),
  Video("Free CCNA | SNMP | Day 40 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=81"),
  Video("Free CCNA | SNMP | Day 40 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=82"),
  Video("Free CCNA | Syslog | Day 41 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=83"),
  Video("Free CCNA | Syslog | Day 41 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=84"),
  Video("Free CCNA | SSH | Day 42 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=85"),
  Video("Free CCNA | SSH | Day 42 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=86"),
  Video("Free CCNA | FTP & TFTP | Day 43 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=87"),
  Video("Free CCNA | FTP & TFTP | Day 43 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=88"),
  Video("Free CCNA | NAT (Part 1) | Day 44 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=89"),
  Video("Free CCNA | Static NAT | Day 44 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=90"),
  Video("Free CCNA | NAT (part 2) | Day 45 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=91"),
  Video("Free CCNA | Dynamic NAT | Day 45 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=92"),
  Video("Free CCNA | QoS (Part 1) | Day 46 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=93"),
  Video("Free CCNA | Voice VLANs | Day 46 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=94"),
  Video("Free CCNA | QoS (Part 2) | Day 47 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=95"),
  Video("Free CCNA | QoS | Day 47 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=96"),
  Video("Free CCNA | Security Fundamentals | Day 48 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=97"),
  Video("Free CCNA | Kali Linux Demo | Day 48 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=98"),
  Video("Free CCNA | Port Security | Day 49 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=99"),
  Video("Free CCNA | Port Security | Day 49 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=100"),
  Video("Free CCNA | DHCP Snooping | Day 50 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=101"),
  Video("Free CCNA | DHCP Snooping | Day 50 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=102"),
  Video("Free CCNA | Dynamic ARP Inspection | Day 51 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=103"),
  Video("Free CCNA | Dynamic ARP Inspection | Day 51 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=104"),
  Video("Free CCNA | LAN Architectures | Day 52 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=105"),
  Video("Free CCNA | STP & FHRP Synchronization | Day 52 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=106"),
  Video("Free CCNA | WAN Architectures | Day 53 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=107"),
  Video("Free CCNA | GRE Tunnels | Day 53 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=108"),
  Video("Free CCNA | Virtualization & Cloud | Day 54 (part 1) | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=109"),
  Video("Free CCNA | Containers | Day 54 (part 2) | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=110"),
  Video("Free CCNA | VRF | Day 54 (part 3) | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=111"),
  Video("Free CCNA | Oracle VirtualBox | Day 54 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=112"),
  Video("Free CCNA | Wireless Fundamentals | Day 55 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=113"),
  Video("Free CCNA | Wireless Architectures | Day 56 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=114"),
  Video("Free CCNA | Wireless Security | Day 57 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=115"),
  Video("Free CCNA | Wireless Configuration | Day 58 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=116"),
  Video("Free CCNA | Wireless LANs | Day 58 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=117"),
  Video("Intro to Network Automation | CCNA 200-301 Day 59 (part 1)", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=118"),
  Video("AI & Machine Learning | CCNA 200-301 Day 59 (part 2)", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=119"),
  Video("Free CCNA | JSON, XML, & YAML | Day 60 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=120"),
  Video("Free CCNA | REST APIs | Day 61 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=121"),
  Video("REST API Authentication | CCNA 200-301 Day 61 (part 2)", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=122"),
  Video("Free CCNA | Software-Defined Networking | Day 62 | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=123"),
  Video("Free CCNA | Ansible, Puppet, & Chef | Day 63 (part 1) | CCNA 200-301 Complete Course", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=124"),
  Video("Terraform | CCNA 200-301 Day 63 (part 2)", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=125"),
  Video("Complete Network Configuration // CCNA Mega Lab! / OSPF, VLANs, STP, DHCP, Security, Wireless + more", "https://www.youtube.com/playlist?list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=126"),
];