import 'package:flutter/material.dart';


// 1. ADD THIS CLASS DEFINITION (This fixes all 127 errors)

class Video {
  String title;
  String url;
  bool done;

  bool isDeleted;
  DateTime? deletedAt;

  Video(
      this.title,
      this.url, {
        this.done = false,
        this.isDeleted = false,
        this.deletedAt,
      });

  Map<String, dynamic> toJson() => {
    "title": title,
    "url": url,
    "done": done,
    "isDeleted": isDeleted,
    "deletedAt": deletedAt?.toIso8601String(),
  };

  factory Video.fromJson(Map<String, dynamic> json) {
    return Video(
      json["title"],
      json["url"],
      done: json["done"] ?? false,
      isDeleted: json["isDeleted"] ?? false,
      deletedAt: json["deletedAt"] != null
          ? DateTime.parse(json["deletedAt"])
          : null,
    );
  }
}

List<Video> videos = [
  Video("Free CCNA | Network Devices | Day 1 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=H8W9oMNSuwo&list=WL&index=2"),
  Video("Free CCNA | Anki Flashcards | Day 1 Extra | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=6Atw8oMtVTA"),
  Video("Free CCNA | Packet Tracer Introduction | Day 1 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=a1Im6GYaSno"),
  Video("Free CCNA | Interfaces and Cables | Day 2 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=ieTH5lVhNaY"),
  Video("Free CCNA | Connecting Devices | Day 2 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=K6Qt23sY68Y&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=5"),
  Video("How the TCP/IP Model Actually Works | CCNA Day 3", "https://www.youtube.com/watch?v=yM-XNq9ADlI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=6"),
  Video("Free CCNA | OSI Model | Day 3 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=7nmYoL0t2tU&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=7&pp=iAQB0gcJCVELAYcqIYzv"),
  Video("Free CCNA | Intro to the CLI | Day 4 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=IYbtai7Nu2g&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=8&pp=iAQB"),
  Video("Free CCNA | Basic Device Security | Day 4 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=SDocmq1c05s&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=9&pp=iAQB"),
  Video("Free CCNA | Ethernet LAN Switching (Part 1) | Day 5 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=u2n762WG0Vo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=10&pp=iAQB"),
  Video("Free CCNA | Ethernet LAN Switching (Part 2) | Day 6 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=5q1pqdmdPjo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=11&pp=iAQB0gcJCZULAYcqIYzv"),
  Video("Free CCNA | Analyzing Ethernet Switching | Day 6 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Ig0dSaOQDI8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=12&pp=iAQB"),
  Video("Free CCNA | IPv4 Addressing (Part 1) | Day 7 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=3ROdsfEUuhs&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=13&pp=iAQB"),
  Video("Free CCNA | IPv4 Addressing (Part 2) | Day 8 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=FiAatRd84XI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=14&pp=iAQB"),
  Video("Free CCNA | Configuring IP Addresses | Day 8 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=e1jbvyMeS5I&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=15&pp=iAQB"),
  Video("Free CCNA | Switch Interfaces | Day 9 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=cCqluocfQe0&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=16&pp=iAQB"),
  Video("Free CCNA | Configuring Interfaces | Day 9 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=rzDb5DoBKRk&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=17&pp=iAQB"),
  Video("Free CCNA | IPv4 Header | Day 10 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=aQB22y4liXA&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=18&pp=iAQB"),
  Video("Free CCNA | Routing Fundamentals | Day 11 (part 1) | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=aHwAm8GYbn8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=19&pp=iAQB"),
  Video("Free CCNA | Static Routing | Day 11 (part 2) | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=YCv4-_sMvYE&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=20&pp=iAQB"),
  Video("Free CCNA | Configuring Static Routes | Day 11 Lab 1 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=XHxOtIav2k8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=21&pp=iAQB"),
  Video("Free CCNA | Troubleshooting Static Routes | Day 11 Lab 2 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=3z8YGEVFTiA&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=22&pp=iAQB0gcJCZULAYcqIYzv"),
  Video("Free CCNA | The Life of a Packet | Day 12 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=4YrYV2io3as&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=23&pp=iAQB"),
  Video("Free CCNA | Life of a Packet | Day 12 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=bfsEqDeHbpI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=24&pp=iAQB"),
  Video("Free CCNA | Subnetting (Part 1) | Day 13 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=bQ8sdpGQu8c&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=25&pp=iAQB"),
  Video("Free CCNA | Subnetting (Part 2) | Day 14 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=IGhd-0di0Qo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=26&pp=iAQB"),
  Video("Free CCNA | Subnetting (Part 3 - VLSM) | Day 15 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=z-JqCedc9EI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=27&pp=iAQB"),
  Video("Free CCNA | Subnetting (VLSM) | Day 15 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Rn_E1Qv8--I&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=28&pp=iAQB"),
  Video("Free CCNA | VLANs (Part 1) | Day 16 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=cjFzOnm6u1g&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=29&pp=iAQB"),
  Video("Free CCNA | VLANs (Part 1) | Day 16 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=-tq7f3xtyLQ&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=30&pp=iAQB0gcJCZULAYcqIYzv"),
  Video("Free CCNA | VLANs (Part 2) | Day 17 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Jl9OOzNaBDU&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=31&pp=iAQB"),
  Video("Free CCNA | VLANs (Part 2) | Day 17 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=iRkFE_lpYgc&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=32&pp=iAQB"),
  Video("Free CCNA | VLANs (Part 3) | Day 18 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=OkPB028l2eE&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=33&pp=iAQB"),
  Video("Free CCNA | VLANs (Part 3) | Day 18 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=MQcCr3QW1vE&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=34&pp=iAQB"),
  Video("Free CCNA | DTP/VTP | Day 19 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=JtQV_0Sjszg&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=35&pp=iAQB"),
  Video("Free CCNA | DTP/VTP | Day 19 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=ngTns2vF_44&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=36&pp=iAQB"),
  Video("Free CCNA | Spanning Tree Protocol (Part 1) | Day 20 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=j-bK-EFt9cY&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=37&pp=iAQB"),
  Video("Free CCNA | Analyzing STP | Day 20 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Ev9gy7B5hx0&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=38&pp=iAQB"),
  Video("Free CCNA | Spanning Tree Protocol (Part 2) | Day 21 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=nWpldCc8msY&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=39&pp=iAQB"),
  Video("PortFast (STP Toolkit) | CCNA 200-301 Day 21 (part 1)", "https://www.youtube.com/watch?v=zqzppl4LOwk&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=40&pp=iAQB"),
  Video("BPDU Guard & BPDU Filter (STP Toolkit) | CCNA 200-301 Day 21 (part 2)", "https://www.youtube.com/watch?v=jfC_AeJnuhY&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=41&pp=iAQB"),
  Video("Root Guard (STP Toolkit) | CCNA 200-301 Day 21 (part 3)", "https://www.youtube.com/watch?v=2XE_PgkvSic&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=42&pp=iAQB"),
  Video("Loop Guard (STP Toolkit) | CCNA 200-301 Day 21 (part 4)", "https://www.youtube.com/watch?v=uJ5_Klha0ig&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=43&pp=iAQB"),
  Video("Free CCNA | Configuring STP (PVST+) | Day 21 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=5rpaeJNig2o&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=44&pp=iAQB"),
  Video("Free CCNA | Rapid Spanning Tree Protocol | Day 22 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=EpazNsLlPps&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=45&pp=iAQB"),
  Video("Free CCNA | Rapid STP | Day 22 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=YG7r4XHy2JU&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=46&pp=iAQB"),
  Video("Free CCNA | EtherChannel | Day 23 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=xuo69Joy_Nc&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=47&pp=iAQB"),
  Video("Free CCNA | Configuring EtherChannel | Day 23 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=8gKF2fMMjA8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=48&pp=iAQB"),
  Video("Free CCNA | Dynamic Routing | Day 24 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=xSTgb8JLkvs&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=49&pp=iAQB"),
  Video("Free CCNA | Floating Static Routes | Day 24 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=KuKC0G3LZc8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=50&pp=iAQB"),
  Video("Free CCNA | RIP & EIGRP | Day 25 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=N8PiZDld6Zc&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=51&pp=iAQB"),
  Video("Free CCNA | Configuring EIGRP | Day 25 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=ffnJ5oBIObY&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=52&pp=iAQB"),
  Video("Free CCNA | OSPF Part 1 | Day 26 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=pvuaoJ9YzoI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=53&pp=iAQB"),
  Video("Free CCNA | Configuring OSPF (1) | Day 26 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=LeLRWjfylcs&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=54&pp=iAQB"),
  Video("Free CCNA | OSPF Part 2 | Day 27 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=VtzfTA21ht0&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=55&pp=iAQB"),
  Video("Free CCNA | Configuring OSPF (2) | Day 27 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=UEyQW-EcnY8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=56&pp=iAQB"),
  Video("Free CCNA | OSPF Part 3 | Day 28 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=3ew26ujkiDI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=57&pp=iAQB"),
  Video("Free CCNA | Configuring OSPF (3) | Day 28 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Goekjm3bK5o&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=58&pp=iAQB"),
  Video("Free CCNA | First Hop Redundancy Protocols | Day 29 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=43WnpwQMolo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=59&pp=iAQB"),
  Video("Free CCNA | Configuring HSRP | Day 29 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=uho5Z2nFhb8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=60&pp=iAQB"),
  Video("Free CCNA | TCP & UDP | Day 30 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=LIEACBqlntY&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=61&pp=iAQB"),
  Video("Free CCNA | Wireshark Demo (TCP/UDP) | Day 30 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=pJKFahkqMU8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=62&pp=iAQB"),
  Video("Free CCNA | IPv6 Part 1 | Day 31 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=ZNuXyOXae5U&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=63&pp=iAQB"),
  Video("Free CCNA | Configuring IPv6 (Part 1) | Day 31 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=BdsIahtrWIA&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=64&pp=iAQB"),
  Video("Free CCNA | IPv6 Part 2 | Day 32 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=BrTMMOXFhDU&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=65&pp=iAQB"),
  Video("Free CCNA | Configuring IPv6 (Part 2) | Day 32 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Zfhpd7dl6QI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=66&pp=iAQB"),
  Video("Free CCNA | IPv6 Part 3 | Day 33 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=rwkHfsWQwy8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=67&pp=iAQB"),
  Video("Free CCNA | Configuring IPv6 (Part 3) | Day 33 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=WSBEVFANMmc&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=68&pp=iAQB"),
  Video("Free CCNA | Standard ACLs | Day 34 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=z023_eRUtSo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=69&pp=iAQB"),
  Video("Free CCNA | Standard ACLs | Day 34 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=sJ8PXmiAkvs&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=70&pp=iAQB"),
  Video("Free CCNA | Extended ACLs | Day 35 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=dUttKY_CNXE&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=71&pp=iAQB"),
  Video("Free CCNA | Extended ACLs | Day 35 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=1cuMzWBrEYs&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=72&pp=iAQB"),
  Video("Free CCNA | CDP & LLDP | Day 36 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=_hnMZBzXRRk&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=73&pp=iAQB"),
  Video("Free CCNA | CDP & LLDP | Day 36 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=4s8qqL7R9W8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=74&pp=iAQB0gcJCZULAYcqIYzv"),
  Video("Free CCNA | NTP | Day 37 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=qGJaJx7OfUo&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=75&pp=iAQB"),
  Video("Free CCNA | NTP | Day 37 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Miys7Ft9wWI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=76&pp=iAQB"),
  Video("Free CCNA | DNS | Day 38 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=4C6eeQes4cs&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=77&pp=iAQB"),
  Video("Free CCNA | DNS | Day 38 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=7D_FapNrRUM&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=78&pp=iAQB0gcJCZULAYcqIYzv"),
  Video("Free CCNA | DHCP | Day 39 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=hzkleGAC2_Y&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=79&pp=iAQB0gcJCZULAYcqIYzv"),
  Video("Free CCNA | DHCP | Day 39 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=cgMsoIQB9Wk&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=80&pp=iAQB"),
  Video("Free CCNA | SNMP | Day 40 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=HXu0Ifj0oWU&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=81&pp=iAQB"),
  Video("Free CCNA | SNMP | Day 40 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=v8WxIytUdS4&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=82&pp=iAQB"),
  Video("Free CCNA | Syslog | Day 41 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=RaQPSKQ4J5A&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=83&pp=iAQB"),
  Video("Free CCNA | Syslog | Day 41 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=-R_CYM6Wm-Y&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=84&pp=iAQB"),
  Video("Free CCNA | SSH | Day 42 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=AvgYqI2qSD4&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=85&pp=iAQB"),
  Video("Free CCNA | SSH | Day 42 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=QnHq7iCOtTc&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=86&pp=iAQB"),
  Video("Free CCNA | FTP & TFTP | Day 43 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=50hcfsoBf4Q&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=87&pp=iAQB"),
  Video("Free CCNA | FTP & TFTP | Day 43 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=W9PLvA2wZ28&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=88&pp=iAQB"),
  Video("Free CCNA | NAT (Part 1) | Day 44 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=2TZCfTgopeg&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=89&pp=iAQB"),
  Video("Free CCNA | Static NAT | Day 44 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=vir6n_NVZFw&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=90&pp=iAQB"),
  Video("Free CCNA | NAT (part 2) | Day 45 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=kILDNs4KjYE&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=91&pp=iAQB"),
  Video("Free CCNA | Dynamic NAT | Day 45 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=vNs1xxiwGJs&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=92&pp=iAQB"),
  Video("Free CCNA | QoS (Part 1) | Day 46 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=H6FKJMiiL6E&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=93&pp=iAQB0gcJCZULAYcqIYzv"),
  Video("Free CCNA | Voice VLANs | Day 46 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=kGX76QNIjsE&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=94&pp=iAQB"),
  Video("Free CCNA | QoS (Part 2) | Day 47 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=4vurfhVjcMM&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=95&pp=iAQB"),
  Video("Free CCNA | QoS | Day 47 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=63tD4t8189k&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=96&pp=iAQB"),
  Video("Free CCNA | Security Fundamentals | Day 48 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=VvFuieyTTSw&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=97&pp=iAQB"),
  Video("Free CCNA | Kali Linux Demo | Day 48 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=EBs47-0ZD-A&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=98&pp=iAQB"),
  Video("Free CCNA | Port Security | Day 49 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=sHN3jOJIido&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=99&pp=iAQB"),
  Video("Free CCNA | Port Security | Day 49 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=zZwhrxKeGj8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=100&pp=iAQB"),
  Video("Free CCNA | DHCP Snooping | Day 50 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=qYYeg2kz1yE&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=101&pp=iAQB"),
  Video("Free CCNA | DHCP Snooping | Day 50 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=YMom_e545H4&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=102&pp=iAQB"),
  Video("Free CCNA | Dynamic ARP Inspection | Day 51 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=HwbTKaIvL6s&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=103&pp=iAQB"),
  Video("Free CCNA | Dynamic ARP Inspection | Day 51 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=oLF2mbmYMAk&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=104&pp=iAQB"),
  Video("Free CCNA | LAN Architectures | Day 52 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=PvyEcLhmNBk&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=105&pp=iAQB"),
  Video("Free CCNA | STP & FHRP Synchronization | Day 52 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=BgIEhyoETgU&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=106&pp=iAQB"),
  Video("Free CCNA | WAN Architectures | Day 53 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=BW3fQgdf4-w&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=107&pp=iAQB"),
  Video("Free CCNA | GRE Tunnels | Day 53 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=_MMuU5viinM&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=108&pp=iAQB"),
  Video("Free CCNA | Virtualization & Cloud | Day 54 (part 1) | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=_S3greGajJA&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=109&pp=iAQB"),
  Video("Free CCNA | Containers | Day 54 (part 2) | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=K731pAS22Aw&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=110&pp=iAQB"),
  Video("Free CCNA | VRF | Day 54 (part 3) | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Ge4644KUvh4&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=111&pp=iAQB"),
  Video("Free CCNA | Oracle VirtualBox | Day 54 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=swqADfQk2jM&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=112&pp=iAQB"),
  Video("Free CCNA | Wireless Fundamentals | Day 55 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=zuYiktLqNYQ&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=113&pp=iAQB"),
  Video("Free CCNA | Wireless Architectures | Day 56 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=uX1h0F6wpBY&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=114&pp=iAQB"),
  Video("Free CCNA | Wireless Security | Day 57 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=wHXKo9So5y8&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=115&pp=iAQB"),
  Video("Free CCNA | Wireless Configuration | Day 58 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=r9o6GFI87go&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=116&pp=iAQB"),
  Video("Free CCNA | Wireless LANs | Day 58 Lab | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Il8ev78fcqw&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=117&pp=iAQB"),
  Video("Intro to Network Automation | CCNA 200-301 Day 59 (part 1)", "https://www.youtube.com/watch?v=4tsBgMCPVuc&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=118&pp=iAQB"),
  Video("AI & Machine Learning | CCNA 200-301 Day 59 (part 2)", "https://www.youtube.com/watch?v=Fn_kAv35W5A&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=119&pp=iAQB"),
  Video("Free CCNA | JSON, XML, & YAML | Day 60 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=nohde2-QNJ4&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=120&pp=iAQB"),
  Video("Free CCNA | REST APIs | Day 61 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Luei0p-2h10&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=121&pp=iAQB"),
  Video("REST API Authentication | CCNA 200-301 Day 61 (part 2)", "https://www.youtube.com/watch?v=bmqr_xpt6sc&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=122&pp=iAQB"),
  Video("Free CCNA | Software-Defined Networking | Day 62 | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=7HhWCeXDTpA&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=123&pp=iAQB"),
  Video("Free CCNA | Ansible, Puppet, & Chef | Day 63 (part 1) | CCNA 200-301 Complete Course", "https://www.youtube.com/watch?v=Kog9gHTjALI&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=124&pp=iAQB"),
  Video("Terraform | CCNA 200-301 Day 63 (part 2)", "https://www.youtube.com/watch?v=VAwUaffejWU&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=125&pp=iAQB"),
  Video("Complete Network Configuration // CCNA Mega Lab! / OSPF, VLANs, STP, DHCP, Security, Wireless + more", "https://www.youtube.com/watch?v=2p7-MluKAgE&list=PLxbwE86jKRgMpuZuLBivzlM8s2Dk5lXBQ&index=126&t=26s&pp=iAQB"),
];